trigger:
- master

jobs:
- job: BuildAndTest
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - script: |
      npm install
      npm run lint
      npm run build
      npm test
- job: RunE2E
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - script: |
      npm install
      npm run build
      npm run e2e
