trigger:
- master

jobs:
- job: BuildAndTest
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - script: npm install
  - script: npm run lint
  - script: npm run build
  - script: npm test
- job: RunE2E
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - script: npm install
  - script: npm run build
  - script: npm run e2e
